defmodule Minex.Metadata do
  @moduledoc false
  defstruct [
    # User supplied.
    bucket: nil,
    object: nil,
    query: nil,
    custom_header: nil,
    expires: nil,

    # Generated by our internal code.
    bucket_location: nil,
    content_body: nil,
    content_length: nil,
    content_md5_base64: nil,
    content_sha256_hex: nil
  ]

  @type t :: %__MODULE__{
          bucket: String.t(),
          object: String.t(),
          query: map(),
          custom_header: list(),
          expires: boolean(),
          bucket_location: String.t(),
          content_body: String.t(),
          content_length: pos_integer(),
          content_md5_base64: String.t(),
          content_sha256_hex: String.t()
        }

  @type metadata :: t()
end
